version: '3.8'

services:
  postgres:
    image: postgres:14.10
    container_name: postgres_container
    environment:
      POSTGRES_DB: transactions-pay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-net

volumes:
  pgdata:

networks:
  spring-net:
    driver: bridge